#### Data Cleaning - Alcohol-Related Hospital Statistics by Council Area (Scotland)

##### Objective
Prepare a **clean, analysis-ready dataset** for downstream Python analysis and Power BI reporting.

**Primary outcome variable:**
- easr_patients (European age-standardised rate per 100,000)

In [0]:
#Import python libraries

import numpy as np
import pandas as pd
from pathlib import Path

In [0]:
# Project paths

DATA_DIR = Path('../data')
RAW_DIR = DATA_DIR / 'raw'
PROCESSED_DIR = DATA_DIR / 'processed'
FIGURES_DIR = Path('../figures')

In [0]:
#Load raw data - ARHS dataset by council area

if Path('/Volumes').exists():
    RAW_DIR = Path('/Volumes/group_project_wfs2025/default/arhs')
else:
    RAW_DIR = Path('../data/raw')

arhs_council_df = pd.read_csv(RAW_DIR/'ARHS_byCouncilArea.csv')

arhs_council_df

         _id  ... AverageNumberOfStaysPerPatient
0          1  ...                            1.1
1          2  ...                            1.1
2          3  ...                            1.2
3          4  ...                            1.2
4          5  ...                            1.2
...      ...  ...                            ...
20099  20100  ...                            1.4
20100  20101  ...                            1.3
20101  20102  ...                            1.4
20102  20103  ...                            1.3
20103  20104  ...                            1.3

[20104 rows x 19 columns]

In [0]:
#Summary info
print(arhs_council_df.info())

#Duplicate values
print(arhs_council_df.duplicated().sum())

#Null values
print(arhs_council_df.isna().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20104 entries, 0 to 20103
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   _id                             20104 non-null  int64
 1   Condition                       20104 non-null  object
 2   ICD10                           17415 non-null  object
 3   ICD10QF                         6253 non-null   object
 4   SMRType                         20104 non-null  object
 5   FinancialYear                   20104 non-null  object
 6   CA                              20104 non-null  object
 7   CAQF                            1096 non-null   object
 8   EASRStays                       20104 non-null  float64
 9   EASRPatients                    20104 non-null  float64
 10  EASRNewPatients                 20104 non-null  float64
 11  EASRNewPatientsQF               7440 non-null   object
 12  NumberOfStays                   20104 non-null  int64
 13  NumberOfStaysQF                 0 non-null      float64
 14  NumberOfPatients                20104 non-null  int64
 15  NumberOfPatientsQF              0 non-null      float64
 16  NumberOfNewPatients             20104 non-null  int64
 17  NumberOfNewPatientsQF           7440 non-null   object
 18  AverageNumberOfStaysPerPatient  20104 non-null  float64
dtypes: float64(6), int64(4), object(9)
memory usage: 2.9+ MB
None
0
_id                                   0
Condition                             0
ICD10                              2689
ICD10QF                           13851
SMRType                               0
FinancialYear                         0
CA                                    0
CAQF                              19008
EASRStays                             0
EASRPatients                          0
EASRNewPatients                       0
EASRNewPatientsQF                 12664
NumberOfStays                         0
NumberOfStaysQF                   20104
NumberOfPatients                      0
NumberOfPatientsQF                20104
NumberOfNewPatients                   0
NumberOfNewPatientsQF             12664
AverageNumberOfStaysPerPatient        0
dtype: int64

In [0]:
#Drop columns - not necessary for further analysis
#Drop the following columns - NumberOfStaysQF, NumberOfPatientsQF, NumberOfNewPatientsQF, EASRNewPatientsQF, CAQF, ICD10QF, ICD10

arhs_council_df.drop(
    ['NumberOfStaysQF', 'NumberOfPatientsQF', 'NumberOfNewPatientsQF', 'EASRNewPatientsQF', 'CAQF', 'ICD10QF', 'ICD10'],
    axis=1,
    inplace = True
)

arhs_council_df

         _id  ... AverageNumberOfStaysPerPatient
0          1  ...                            1.1
1          2  ...                            1.1
2          3  ...                            1.2
3          4  ...                            1.2
4          5  ...                            1.2
...      ...  ...                            ...
20099  20100  ...                            1.4
20100  20101  ...                            1.3
20101  20102  ...                            1.4
20102  20103  ...                            1.3
20103  20104  ...                            1.3

[20104 rows x 12 columns]

In [0]:
#Uniqe values in each columns
print(arhs_council_df.nunique())

print('\nUniqe values of Financial Year: ')
print(arhs_council_df['FinancialYear'].unique())

print('\nUniques values of Council Areas: ')
print(arhs_council_df['CA'].unique())

print('\nUnique values of SMRType: ')
print(arhs_council_df['SMRType'].unique())

print('\nUnique values of Condition: ')
print(arhs_council_df['Condition'].unique())

_id                               20104
Condition                            20
SMRType                               3
FinancialYear                        43
CA                                   33
EASRStays                          5526
EASRPatients                       4703
EASRNewPatients                    2439
NumberOfStays                      1365
NumberOfPatients                   1154
NumberOfNewPatients                 610
AverageNumberOfStaysPerPatient       32
dtype: int64

Uniqe values of Financial Year:
['1981/82' '1982/83' '1983/84' '1984/85' '1985/86' '1986/87' '1987/88'
 '1988/89' '1989/90' '1990/91' '1991/92' '1992/93' '1993/94' '1994/95'
 '1995/96' '1996/97' '1997/98' '1998/99' '1999/00' '2000/01' '2001/02'
 '2002/03' '2003/04' '2004/05' '2005/06' '2006/07' '2007/08' '2008/09'
 '2009/10' '2010/11' '2011/12' '2012/13' '2013/14' '2014/15' '2015/16'
 '2016/17' '2017/18' '2018/19' '2019/20' '2020/21' '2021/22' '2022/23'
 '2023/24']

Uniques values of Council Areas:
['S92000003' 'S12000033' 'S12000034' 'S12000041' 'S12000035' 'S12000008'
 'S12000021' 'S12000028' 'S12000026' 'S12000005' 'S12000006' 'S12000045'
 'S12000039' 'S12000042' 'S12000036' 'S12000014' 'S12000047' 'S12000049'
 'S12000017' 'S12000018' 'S12000050' 'S12000029' 'S12000010' 'S12000040'
 'S12000019' 'S12000020' 'S12000013' 'S12000023' 'S12000048' 'S12000038'
 'S12000011' 'S12000027' 'S12000030']

Unique values of SMRType:
['SMR01' 'SMR04' 'Combined']

Unique values of Condition:
['All alcohol conditions' 'Alcoholic Liver Disease: All'
 'ALD - Fatty Liver' 'ALD - Alcoholic Hepatitis' 'ALD - Cirrhosis'
 'ALD - Hepatic Failure' 'ALD - Unspecified'
 'Mental & behavioural disorders due to use of alcohol: All'
 'M&B - Acute Intoxication' 'M&B - Harmful Use'
 'M&B - Alcohol Dependence syndrome' 'M&B - Withdrawal state'
 'M&B - Withdrawal state with delirium'
 'M&B - Psychotic and amnesic disorders'
 'M&B - Other mental and behavioural disorders'
 'Alcohol Related Brain Damage' 'Toxic Effects of Alcohol'
 'Alcoholic Cardiomyopathy' 'Alcoholic Gastritis'
 'Alcohol-induced pancreatitis']

In [0]:
#FinancialYear column

#Rename FinancalYear column to FinancialYear_label
arhs_council_df.rename(
    columns = {'FinancialYear' : 'FinancialYear_label'},
    inplace = True
)

#Convert object datatype to str

arhs_council_df['FinancialYear_label'] = arhs_council_df['FinancialYear_label'].astype('string')

#Extarct first four character from FinancialYear_label as FinancialYear

arhs_council_df['FinancialYear'] = (
    arhs_council_df['FinancialYear_label']
    .str.extract(r'(\d{4})', expand = False)
    .astype('int')
)

#Validate change

print(arhs_council_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20104 entries, 0 to 20103
Data columns (total 13 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   _id                             20104 non-null  int64
 1   Condition                       20104 non-null  object
 2   SMRType                         20104 non-null  object
 3   FinancialYear_label             20104 non-null  string
 4   CA                              20104 non-null  object
 5   EASRStays                       20104 non-null  float64
 6   EASRPatients                    20104 non-null  float64
 7   EASRNewPatients                 20104 non-null  float64
 8   NumberOfStays                   20104 non-null  int64
 9   NumberOfPatients                20104 non-null  int64
 10  NumberOfNewPatients             20104 non-null  int64
 11  AverageNumberOfStaysPerPatient  20104 non-null  float64
 12  FinancialYear                   20104 non-null  int64
dtypes: float64(4), int64(5), object(3), string(1)
memory usage: 2.0+ MB
None

In [0]:
#Harmonise column names

arhs_council_df.rename(
    columns={
        'Condition': 'condition',
        'SMRType': 'smr_type_code',
        'FinancialYear_label': 'financial_year_label',
        'CA': 'council_code',
        'EASRStays': 'easr_stays',
        'EASRPatients': 'easr_patients',
        'EASRNewPatients': 'easr_new_patients',
        'NumberOfStays': 'number_of_stays',
        'NumberOfPatients': 'number_of_patients',
        'NumberOfNewPatients': 'number_of_new_patients',
        'AverageNumberOfStaysPerPatient': 'average_number_of_stays_per_patient',
        'FinancialYear': 'financial_year'
    },
    inplace=True
)

In [0]:
#Create dictionary for mapping council areas

COUNCIL_CODE_MAP = {
    'S92000003' :'Scotland',
    'S12000005' : 'Clackmannanshire',
    'S12000006' : 'Dumfries and Galloway',
    'S12000008' : 'East Ayrshire',
    'S12000010' : 'East Lothian',
    'S12000011' : 'East Renfrewshire',
    'S12000013' : 'Na h-Eileanan Siar',
    'S12000014' : 'Falkirk',
    'S12000017' : 'Highland',
    'S12000018' : 'Inverclyde',
    'S12000019' : 'Midlothian',
    'S12000020' : 'Moray',
    'S12000021' : 'North Ayrshire',
    'S12000023' : 'Orkney Islands',
    'S12000026' : 'Scottish Borders',
    'S12000027' : 'Shetland Islands',
    'S12000028' : 'South Ayrshire',
    'S12000029' : 'South Lanarkshire',
    'S12000030' : 'Stirling',
    'S12000033' : 'Aberdeen City',
    'S12000034' : 'Aberdeenshire',
    'S12000035' : 'Argyll and Bute',
    'S12000036' : 'City of Edinburgh',
    'S12000038' : 'Renfrewshire',
    'S12000039' : 'West Dunbartonshire',
    'S12000040' : 'West Lothian',
    'S12000041' : 'Angus',
    'S12000042' : 'Dundee City',
    'S12000045' : 'East Dunbartonshire',
    'S12000047' : 'Fife',
    'S12000048' : 'Perth and Kinross',
    'S12000049' : 'Glasgow City',
    'S12000050' : 'North Lanarkshire', 
}

SMR_TYPE_MAP = {
    'SMR01' : 'Non-psychiatric',
    'SMR04' : 'Psychiatric',
    'Combined' : 'Combined'
}

#Map council areas and SMR types

arhs_council_df['council_area'] = arhs_council_df['council_code'].map(COUNCIL_CODE_MAP)
arhs_council_df['smr_type'] = arhs_council_df['smr_type_code'].map(SMR_TYPE_MAP)
arhs_council_df

         _id                     condition  ... council_area         smr_type
0          1        All alcohol conditions  ...     Scotland  Non-psychiatric
1          2        All alcohol conditions  ...     Scotland  Non-psychiatric
2          3        All alcohol conditions  ...     Scotland  Non-psychiatric
3          4        All alcohol conditions  ...     Scotland  Non-psychiatric
4          5        All alcohol conditions  ...     Scotland  Non-psychiatric
...      ...                           ...  ...          ...              ...
20099  20100  Alcohol-induced pancreatitis  ...     Scotland  Non-psychiatric
20100  20101  Alcohol-induced pancreatitis  ...     Scotland  Non-psychiatric
20101  20102  Alcohol-induced pancreatitis  ...     Scotland  Non-psychiatric
20102  20103  Alcohol-induced pancreatitis  ...     Scotland  Non-psychiatric
20103  20104  Alcohol-induced pancreatitis  ...     Scotland  Non-psychiatric

[20104 rows x 15 columns]

In [0]:
#New variable
string_cols = [
    '_id', 'financial_year_label', 'condition',
    'council_code', 'council_area', 'smr_type'
]

#Ensure dataypes in each columns
for col in string_cols:
    arhs_council_df[col] = arhs_council_df[col].astype('string')


#Validate clean dataset
print('\nSummary info of clean dataset: ')
print(arhs_council_df.info())

#Unique values of clean dataset
print('\nUnique values of clean dataset: ')
print(arhs_council_df.nunique())

Summary info of clean dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20104 entries, 0 to 20103
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   _id                                  20104 non-null  string
 1   condition                            20104 non-null  string
 2   smr_type_code                        20104 non-null  object
 3   financial_year_label                 20104 non-null  string
 4   council_code                         20104 non-null  string
 5   easr_stays                           20104 non-null  float64
 6   easr_patients                        20104 non-null  float64
 7   easr_new_patients                    20104 non-null  float64
 8   number_of_stays                      20104 non-null  int64
 9   number_of_patients                   20104 non-null  int64
 10  number_of_new_patients               20104 non-null  int64
 11  average_number_of_stays_per_patient  20104 non-null  float64
 12  financial_year                       20104 non-null  int64
 13  council_area                         20104 non-null  string
 14  smr_type                             20104 non-null  string
dtypes: float64(4), int64(4), object(1), string(6)
memory usage: 2.3+ MB
None

Unique values of clean dataset:
_id                                    20104
condition                                 20
smr_type_code                              3
financial_year_label                      43
council_code                              33
easr_stays                              5526
easr_patients                           4703
easr_new_patients                       2439
number_of_stays                         1365
number_of_patients                      1154
number_of_new_patients                   610
average_number_of_stays_per_patient       32
financial_year                            43
council_area                              33
smr_type                                   3
dtype: int64

In [0]:
#Validation check

assert arhs_council_df['financial_year'].notna().all()
assert arhs_council_df['council_area'].notna().all()

In [0]:
#Export clean dataset to csv

if Path('/Volumes').exists():
    PROCESSED_DIR = Path('/Volumes/group_project_wfs2025/default/arhs')
else:
    PROCESSED_DIR = Path('../data/processed')

arhs_council_df.to_csv(
    PROCESSED_DIR / 'ARHS_byCouncilArea_clean.csv',
    index=False
)